# Generated by Django 4.1 on 2022-11-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0002_rename_login_tb_admin_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='category_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
